// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVSqYRrnWL0iHrO7jHazqtUg_ianFLuA',
    appId: '1:670484502155:web:08891464b08f3b0b0ae68e',
    messagingSenderId: '670484502155',
    projectId: 'gram-8c397',
    authDomain: 'gram-8c397.firebaseapp.com',
    storageBucket: 'gram-8c397.appspot.com',
    measurementId: 'G-63P3LE1ST9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNynW6ed3wTprZ42aQI_IxiA4tch1c9Gg',
    appId: '1:670484502155:android:503399317944468c0ae68e',
    messagingSenderId: '670484502155',
    projectId: 'gram-8c397',
    storageBucket: 'gram-8c397.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2mEezzOwYurrRKBzLEgN8kCQ0Fv-GRdM',
    appId: '1:670484502155:ios:236cd33f57390e080ae68e',
    messagingSenderId: '670484502155',
    projectId: 'gram-8c397',
    storageBucket: 'gram-8c397.appspot.com',
    iosBundleId: 'com.example.gram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2mEezzOwYurrRKBzLEgN8kCQ0Fv-GRdM',
    appId: '1:670484502155:ios:236cd33f57390e080ae68e',
    messagingSenderId: '670484502155',
    projectId: 'gram-8c397',
    storageBucket: 'gram-8c397.appspot.com',
    iosBundleId: 'com.example.gram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcVSqYRrnWL0iHrO7jHazqtUg_ianFLuA',
    appId: '1:670484502155:web:5a0b33d51e45c8ef0ae68e',
    messagingSenderId: '670484502155',
    projectId: 'gram-8c397',
    authDomain: 'gram-8c397.firebaseapp.com',
    storageBucket: 'gram-8c397.appspot.com',
    measurementId: 'G-8697D3227W',
  );
}
